NAME: 'ACE'
OUTPUT_DIR: './output/cifar100_im100'
SHOW_STEP: 40
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'


DATASET:
  DATASET: 'CIFAR'
  TRAIN_JSON: './data/cifar100_imbalance100_train.json'
  VALID_JSON: './data/cifar100_imbalance100_valid.json'

BACKBONE:
  TYPE: 'res32_cifar_group'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'LWS'
  BIAS: True

LOSS:
  LOSS_TYPE: 'ResCELoss'

TRAIN:
  USE_AMP: False
  BATCH_SIZE: 128
  MAX_EPOCH: 260
  UNMIX_EPOCH: 20
  NUM_WORKERS: 4
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD_group'
    EXPERT: [0.3, 0.03]
    BASE_LR: 0.2
    MOMENTUM: 0.9
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [200, 240]
    LR_FACTOR: 0.1
    WARM_EPOCH: 0
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'

  DISTRIBUTED: False
  SYNCBN: False

TRANSFORMS:
  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 128
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'
  PRED_FILE: 'cifar100_imbalance100_val_pred'
  LABEL_FILE: 'cifar100_imbalance100_val_lea'
  FEA_FILE: 'cifar100_imbalance100_val_fea'
