NAME: 'res50'
OUTPUT_DIR: './output/ImageNet_LT/'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'

DATASET:
  DATASET: 'iNaturalist'
  TRAIN_JSON: './data/ImageNetLT_train_reorder2.json'
  VALID_JSON: './data/ImageNetLT_test_reorder2.json'

BACKBONE:
  TYPE: 'res50_group'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'LWS'
  BIAS: True

LOSS:
  LOSS_TYPE: 'ResCELoss'

TRAIN:
  USE_AMP: False
  BATCH_SIZE: 256
  MAX_EPOCH: 200
  UNMIX_EPOCH: 20
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'mix_up_group'
    ALPHA: 0.3
  OPTIMIZER:
    TYPE: 'SGD_group'
    BASE_LR: 0.1
    EXPERT: [0.4, 0.1]
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4

  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [140, 180]
    LR_FACTOR: 0.1
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'

  DISTRIBUTED: False
  SYNCBN: False

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip", "color_jitter")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'
  PRED_FILE: 'ImageNetLT_train_pred'
  LABEL_FILE: 'ImageNetLT_train_lea'
  FEA_FILE: 'ImageNetLT_train_fea'